CREATE TABLE IF NOT EXISTS settings (name VARCHAR(80) PRIMARY KEY, value LONGTEXT NOT NULL);
CREATE TABLE IF NOT EXISTS admins (id INT PRIMARY KEY AUTO_INCREMENT, username VARCHAR(60) UNIQUE NOT NULL, password_hash VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS projects (
 id CHAR(36) PRIMARY KEY, owner_hash CHAR(64) NOT NULL, title VARCHAR(160) NOT NULL, description TEXT NOT NULL, author VARCHAR(100) NOT NULL DEFAULT '',
 slug VARCHAR(190) UNIQUE NOT NULL, visibility ENUM('private','unlisted','public') NOT NULL DEFAULT 'private', entry_file VARCHAR(180) NOT NULL DEFAULT 'main.strudel',
 metadata LONGTEXT NOT NULL, tags TEXT NOT NULL, version INT NOT NULL DEFAULT 1, builtin BOOLEAN NOT NULL DEFAULT 0, featured BOOLEAN NOT NULL DEFAULT 0,
 remix_of CHAR(36) NULL, cover_id CHAR(36) NULL, preview_id CHAR(36) NULL, moderation_notes TEXT NULL,
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 INDEX(owner_hash), INDEX(visibility,updated_at), INDEX(remix_of)
);
CREATE TABLE IF NOT EXISTS project_files (id BIGINT AUTO_INCREMENT PRIMARY KEY, project_id CHAR(36) NOT NULL, path VARCHAR(180) NOT NULL, kind ENUM('file','folder') NOT NULL DEFAULT 'file', content MEDIUMTEXT NOT NULL, UNIQUE(project_id,path), FOREIGN KEY(project_id) REFERENCES projects(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS project_revisions (id CHAR(36) PRIMARY KEY, project_id CHAR(36) NOT NULL, snapshot MEDIUMTEXT NOT NULL, reason VARCHAR(80) NOT NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, INDEX(project_id,created_at), FOREIGN KEY(project_id) REFERENCES projects(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS media (id CHAR(36) PRIMARY KEY, owner_hash CHAR(64) NOT NULL, project_id CHAR(36) NULL, kind ENUM('sample','recording','export','cover') NOT NULL, filename VARCHAR(80) NOT NULL, original_name VARCHAR(180) NOT NULL, mime VARCHAR(80) NOT NULL, size BIGINT NOT NULL, duration DOUBLE NOT NULL DEFAULT 0, metadata TEXT NOT NULL, approved BOOLEAN NOT NULL DEFAULT 1, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, INDEX(owner_hash), INDEX(project_id), FOREIGN KEY(project_id) REFERENCES projects(id) ON DELETE SET NULL);
CREATE TABLE IF NOT EXISTS sample_packs (id CHAR(36) PRIMARY KEY, name VARCHAR(120) NOT NULL, description TEXT NOT NULL, license TEXT NOT NULL, enabled BOOLEAN NOT NULL DEFAULT 1, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS sample_pack_items (pack_id CHAR(36) NOT NULL, media_id CHAR(36) NOT NULL, sample_name VARCHAR(100) NOT NULL, PRIMARY KEY(pack_id,media_id), FOREIGN KEY(pack_id) REFERENCES sample_packs(id) ON DELETE CASCADE, FOREIGN KEY(media_id) REFERENCES media(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS activity_log (id BIGINT PRIMARY KEY AUTO_INCREMENT, event VARCHAR(80) NOT NULL, entity_id CHAR(36) NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP);
