"""Create genuine starter topics via the already authenticated gh CLI. Idempotent by title."""
import subprocess,json,pathlib
repo='R_kgDOU4iMsw'
categories={'Announcements':'DIC_kwDOU4iMs84DG3u8','General':'DIC_kwDOU4iMs84DG3u9','Ideas':'DIC_kwDOU4iMs84DG3u_','Q&A':'DIC_kwDOU4iMs84DG3u-','Show and tell':'DIC_kwDOU4iMs84DG3vA'}
posts=[
('Announcements','Welcome to XXC / THUGS(red) — Strudel Sandbox', '''## Code / sound / signal\n\nThe studio is at **https://strudel.xxc.dk**. It opens directly into the official Strudel editor/runtime, with a starter score ready for your first Play.\n\nYou can work across files, shape your own samples, record the master output, generate a code cover, and share a score through the XXC library. The application source is AGPL-3.0-or-later; the original starter samples and built-in scores are CC0.\n\nStart with [Getting Started](https://github.com/kawaiipantsu/strudel-xxc/wiki/Getting-Started), then browse the [library](https://strudel.xxc.dk/library). Safari may ask you to click Enable Audio inside the editor.\n\nThese are opening discussion topics for the project. Bring questions, feedback and your own sounds. **Make noise. Share tools. Keep it open.**'''),
('Q&A','First session: Play, evaluate, hush, save', '''A small starting point:\n\n```javascript\nsetcps(120/60/4)\n$: s("bd*4, [~ sd]*2, hh*8").gain(.4)\n$: n("0 3 7 5").scale("C4:minor").s("triangle").room(.3).gain(.2)\n```\n\n1. Press Play and enable audio if prompted.\n2. Change a pattern. Ctrl/Cmd+Enter evaluates the selection or logical block; Update evaluates the whole file.\n3. Ctrl/Cmd+. hushes. Ctrl/Cmd+S saves.\n4. Open Visuals to see the actual signal and events.\n\nPrivate ownership is tied to this browser’s secure cookie. Export a project ZIP before clearing site data. Public/shared scores never run merely because you open them.\n\nIf your first session gets stuck, reply with browser/OS and the useful Problems message. Keep credentials and private sample links out of the post.'''),
('Ideas','Feature wishes: what would make your live set easier?', '''Use this thread for workflow ideas. A useful request explains:\n\n- What you are trying to do musically.\n- What takes too many steps or breaks your concentration today.\n- A concrete score or example of the interaction you want.\n- Whether it matters most in the editor, Sample Lab, recording, visuals or live performance.\n\nSplit editing, more control mappings and new visual views are reasonable topics to discuss. Requests are proposals, not promises of delivery. Reproducible bugs belong in [Issues](https://github.com/kawaiipantsu/strudel-xxc/issues).'''),
('Show and tell','Score exchange: share a pattern, explain one idea', '''Post an original Strudel score or a public XXC project link. Include the tempo, sample dependencies, any hardware requirement, and your chosen license.\n\nA short explanation makes a score more useful: what does one transformation do, and what should someone change first?\n\nStarter prompt: make a groove with no more than three voices and one evolving parameter. The bundled original `bd`, `sd`, `hh`, `cp` and `tone` samples are available without a remote pack.\n\nUse Fork / Remix when continuing a library project so its provenance stays visible. Keep code understandable and explain external network/device access.'''),
('Show and tell','Sample swap: original sounds, clear licenses', '''Share sounds you recorded or synthesized, or material with clear redistribution permission. Please include:\n\n- Creator, source and license.\n- Sample rate, channel count and approximate duration.\n- A waveform/audio preview when helpful.\n- A short Strudel pattern that puts the sound to use.\n\nSample Lab can record a microphone, select a region, trim/crop, reverse, fade, normalize and save WAV files into a project. Its Insert into Strudel action supplies the sample map.\n\nDo not upload commercial packs or copyrighted tracks without the right to redistribute them. A public project makes its associated samples link-readable.'''),
('General','Recording and export notes: WAV, MP3, M4A and covers', '''The recorder captures the actual master output as uncompressed float PCM. You can download the original WAV or request FFmpeg exports: 24-bit WAV, 320 kbps MP3, and 256 kbps AAC/M4A.\n\nGenerate a cover in Export / Share before encoding to attach its PNG representation to MP3/M4A. The SVG master remains available separately. Title, artist and comment are editable.\n\nRecording stops at the earlier configured duration or raw byte limit. At 48 kHz stereo, a 32 MB float PCM budget is about 87 seconds. The administrator can adjust limits.\n\nUse this thread for repeatable export/player compatibility observations. Include browser, format, player and a small test case; avoid private capability URLs.'''),
('General','Performance setups: controllers, projectors and browser notes', '''Describe a setup that helps you perform: browser/OS, audio interface, screen/projector arrangement and any MIDI controller. Real hardware observations are useful because automated browser tests cannot certify physical latency or MIDI timing.\n\nControls → Connect MIDI requests permission explicitly. MIDI learn maps a CC to a named control; use `macro("cutoff",1200)` in an ordinary Strudel parameter. System-exclusive messages are blocked.\n\nHydra needs WebGL. OSC needs a separate bridge; the site does not run a Node/OSC backend. WebSerial availability depends on browser restrictions.\n\nA useful post includes a small score and what you measured, rather than a claim that a browser or device always works.'''),
('General','Introduce your sound: community check-in', '''What do you like making with code: minimal rhythms, ambient systems, generative melodies, noisy textures, visuals, something else?\n\nShare a short introduction and, if you like, one project you are happy for others to remix. Newcomers are welcome to start with a four-note pattern.\n\nThis thread is a place to meet other users as the project grows. Keep feedback useful, explain your dependencies, and give credit when building on someone else’s work.''')
]
query='query { repository(owner:"kawaiipantsu",name:"strudel-xxc") { discussions(first:100) { nodes { title url } } } }'
existing=json.loads(subprocess.check_output(['gh','api','graphql','-f','query='+query],text=True))['data']['repository']['discussions']['nodes'];bytitle={p['title']:p['url'] for p in existing};links=[]
for category,title,body in posts:
 if title in bytitle:links.append((title,bytitle[title]));continue
 mutation='mutation($repo:ID!,$cat:ID!,$title:String!,$body:String!){createDiscussion(input:{repositoryId:$repo,categoryId:$cat,title:$title,body:$body}){discussion{url}}}'
 payload={'query':mutation,'variables':{'repo':repo,'cat':categories[category],'title':title,'body':body}}
 out=json.loads(subprocess.check_output(['gh','api','graphql','--input','-'],input=json.dumps(payload),text=True))
 if 'errors' in out:raise RuntimeError(str(out['errors']))
 url=out['data']['createDiscussion']['discussion']['url'];links.append((title,url));print(title+' → '+url)
pathlib.Path('docs/COMMUNITY_THREADS.md').write_text('# Community starter discussions\n\nOpening topics created for real contributions; no fabricated replies or engagement metrics.\n\n'+'\n'.join('- ['+t+']('+u+')' for t,u in links)+'\n')
